# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fce1ec27f1132625a261c29beb701c7b"
name = "Simple Sales"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes,read_orders,read_products,read_script_tags,write_script_tags"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
